# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "/etc/prometheus/first-rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    tls_config:
            ca_file: '/etc/prometheus/grafana.crt'
            insecure_skip_verify: true
    static_configs:
            - targets: ['prometheus.lab.lan:9090']
  - job_name: 'linux'
    scheme: https
    basic_auth:
     username: 'prometheus'
     password: 'lyyQRaTppdHhu0YAeBvUSs0mt0BBzNkC9vJXl2bUOuE='
    tls_config:
            ca_file: '/etc/prometheus/grafana.crt'
            insecure_skip_verify: true
    static_configs:
            - targets: ['prometheus.lab.lan:9100']
  - job_name: 'windows'
    static_configs:
            - targets: ['10.209.10.1:9182']
  - job_name: "blackbox-http"
    metrics_path: "/probe"
    params:
      module: [ "http_2xx" ]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "localhost:9115"
    static_configs:
            - targets: [ "http://10.209.40.1/"  ]
  - job_name: 'demo'
    scheme: https
    tls_config:
            ca_file: '/etc/prometheus/grafana.crt'
            insecure_skip_verify: true
    static_configs:
            - targets:
                    - 'prometheus.lab.lan:9090'
