basic_auth_users:
        prometheus: '$2y$10$VvOQEmD2XEBJ5mfU6amz7ekYHxEL3xYAT3Pc6Nv7ewG7/xJt5T.32'
tls_server_config:
        cert_file: "/etc/node-exporter/grafana.crt"
        key_file: "/etc/node-exporter/grafana.key"
